info:
  version: "@project.version@"
  title: "Volgsys Systems"

server:
  port: 8080

spring:
  main:
    allow-bean-definition-overriding: true
    web-application-type: reactive

  datasource:
    url: jdbc:postgresql://localhost:5432/cleytonsales
    username: postgres
    password:
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  webflux:
    base-path: /
app:
  jwtSecret: cleyton
  jwtExpirationInMs: 3600000
jwt:
  secret: cleyton
  expiration: 360000

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    url: /swagger.yaml
